version: '3.7'
services:
  couchbasedb:
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - 8091:8091
      - 8093:8093
      - 8094:8094
      - 11210:11210
    restart: always
